# Generated by Django 5.2.7 on 2025-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[(None, 'Select user'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='teacher'),
        ),
    ]
