# Generated by Django 5.2.7 on 2025-10-27 11:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_roles_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(blank=True, null=True, unique=True, validators=[users.models.is_umat_id]),
        ),
    ]
