# Generated by Django 5.2.7 on 2025-10-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_id',
            new_name='school_id',
        ),
    ]
