# Generated by Django 5.2.7 on 2025-10-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_students'),
        ('users', '0004_rename_student_id_customuser_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deparment',
            field=models.ForeignKey(blank=True, default='4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.department'),
        ),
    ]
