# Generated by Django 5.2.7 on 2025-10-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_deparment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='deparment',
            new_name='department',
        ),
    ]
