# Generated by Django 5.2.7 on 2025-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='defualt_image.jpg', upload_to='profiles/'),
        ),
    ]
