# Generated by Django 5.2.7 on 2025-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_assignment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
