# Generated by Django 5.2.7 on 2025-11-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_learningmaterial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
